const ProductsData = [
  {
    name: "Solimo Coffee Beans",
    weight: 2,
    cost: 10.73,
    image: "815O9ktyfUL.png",
    country: "brazil",
    best: false,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 1,
    counter: 1,
  },
  {
    name: "Presto Coffee Beans",
    weight: 1,
    cost: 15.99,
    image: "91Ryk2gKejL.png",
    country: "kenya",
    best: false,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 2,
    counter: 1,
  },
  {
    name: "AROMISTICO Coffee",
    weight: 1.5,
    cost: 15.99,
    image: "71qBQnpQFYL.png",
    country: "kenya",
    best: true,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 3,
    counter: 1,
  },
  {
    name: "Movenpick Caffe Crema",
    weight: 1,
    cost: 5.99,
    image: "2458465_2.jpg",
    country: "africa",
    best: true,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 4,
    counter: 1,
  },
  {
    name: "Lavazza Qualita Oro",
    weight: 0.5,
    cost: 3.5,
    image: "2442055-1_3.jpg",
    country: "brazil",
    best: false,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 5,
    counter: 1,
  },
  {
    name: "Dallmayr Prodomo",
    weight: 1,
    cost: 5.8,
    image: "2458322.jpg",
    country: "kenya",
    best: false,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 6,
    counter: 1,
  },
  {
    name: "Fineberry Honduras",
    weight: 1.8,
    cost: 9.4,
    image: "7853462_10.jpg",
    country: "colombia",
    best: false,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 7,
    counter: 1,
  },
  {
    name: "Melitta BellaCrema Selection des Jahres",
    weight: 3,
    cost: 14.8,
    image: "1006683-2.jpg",
    country: "guatemala",
    best: true,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 8,
    counter: 1,
  },
  {
    name: "Lucaffe Mr.Exclusive",
    weight: 1,
    cost: 20.1,
    image: "2462922_9.jpg",
    country: "africa",
    best: true,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 9,
    counter: 1,
  },
  {
    name: "Fineberry Original Blend",
    weight: 2,
    cost: 24.05,
    image: "857753.jpg",
    country: "brazil",
    best: false,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 10,
    counter: 1,
  },
  {
    name: "Merrild Crema",
    weight: 1,
    cost: 12.1,
    image: "1006120-1.jpg",
    country: "kenya",
    best: false,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 11,
    counter: 1,
  },
  {
    name: "KIMBO Top Extreme",
    weight: 1.5,
    cost: 10,
    image: "2947932-1.jpg",
    country: "colombia",
    best: false,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 12,
    counter: 1,
  },
  {
    name: "Julius Meinl Jubilee",
    weight: 1.8,
    cost: 13,
    image: "julius_meinl_1_1_.jpg",
    country: "guatemala",
    best: false,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 13,
    counter: 1,
  },

  {
    name: "Malongo Mexico Istmo",
    weight: 1,
    cost: 30,
    image: "490.jpg",
    country: "brazil",
    best: false,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 14,
    counter: 1,
  },
  {
    name: "Magnum Exotics JAMAICA BLUE MOUNTAIN BLEND",
    weight: 1,
    cost: 13.4,
    image: "2462490-2_1.jpg",
    country: "brazil",
    best: false,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 15,
    counter: 1,
  },
  {
    name: "GetUp Strong Blend",
    weight: 1,
    cost: 10.4,
    image: "6576555.jpg",
    country: "colombia",
    best: false,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 16,
    counter: 1,
  },
  {
    name: "ILLY Monoarabica",
    weight: 1.2,
    cost: 11.24,
    image: "3899291-1_2.jpg",
    country: "africa",
    best: true,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 17,
    counter: 1,
  },
  {
    name: "Kurukahveci Mehmet Efendi Filtre",
    weight: 1,
    cost: 8.4,
    image: "1004822-1.jpg",
    country: "kenya",
    best: true,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 18,
    counter: 1,
  },
  {
    name: "Stefano",
    weight: 0.9,
    cost: 23,
    image: "1006222-1.jpg",
    country: "africa",
    best: true,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odio harum eligendi ex recusandae iusto sequi veniam magni eius ipsam, maxime, cupiditate modi eaque in, impedit similique. Molestias eius sint eos.",
    id: 19,
    counter: 1,
  },
];

export { ProductsData };
